eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: eureka-host1
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-host1
  client:
    service-url:
      defaultZone:
management:
  server:
    port: 8093